version: '3'

services:
  weed:
    image: chrislusf/seaweedfs
    ports:
      - "9333:9333"
      - "8080:8080"
    command: "server -master.volumeSizeLimitMB=500 -volume.max=2"
  simple-web-cache:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - weed
